name: sigmaT
channels:
  - conda-forge
dependencies:
  - python==3.11
  - bottleneck
  - scipy
  - xarray==2023.11.0
  - regionmask
  - cmocean
  - numpy==1.25.2
  - dask
  - pandas
  - statsmodels
  - nc-time-axis
  - cartopy
  - yaml
  - ipykernel
  - matplotlib
  - seaborn
  - netcdf4
  - scikit-learn
  - h5netcdf
  - cfgrib
  - zarr
  - cftime
  - pynio
  - xlrd
  - rasterio
  - openpyxl
  - ca-certificates
  - certifi
  - openssl
  - arch-py
  - sympy
  - pymc==5.8.2
  - numba
  - tbb
  - libpysal
  - esda
  - pip:
    - git+https://github.com/pymc-devs/pymc-experimental.git

